# Site settings
title: Francis Portfolio Site
email: fvargas213@.com
description: |
  My current weaving in the web within Night Agency and personal experiments
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joonxz.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  joonxz

# Build settings
markdown: kramdown
