# Site settings
title: joonxz.github.io
email: fvargas213@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joonxz.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
